# Generated by Django 4.0.4 on 2022-04-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='coment',
            new_name='comment',
        ),
    ]
